export const SURVEILLANCE_RADIUS_M = 5000; // 5km active surveillance zone
export const MAX_GEOFENCES = 80; // Stay under Android's ~100 limit
export const ROUGH_FILTER_DEGREES = 0.05; // ~5.5km bounding box pre-filter

export const CATEGORY_ICON_OPTIONS = [
  'silverware-fork-knife',
  'glass-cocktail',
  'coffee',
  'shopping',
  'palette',
  'run',
  'map-marker',
  'food',
  'pizza',
  'hamburger',
  'ice-cream',
  'cake',
  'beer',
  'wine',
  'tea',
  'cup',
  'cart',
  'store',
  'tshirt-crew',
  'hanger',
  'book-open-variant',
  'movie-open',
  'music',
  'theater',
  'camera',
  'brush',
  'basketball',
  'soccer',
  'tennis',
  'swim',
  'bike',
  'dumbbell',
  'hospital-box',
  'school',
  'office-building',
  'home',
  'tree',
  'flower',
  'heart',
  'star',
] as const;
